name: pydrograph_ci
channels:
- conda-forge
- defaults
dependencies:
- python
- ipython
- jupyter
- notebook
- ipykernel
- numpy
- scipy
- pandas
- fiona
- shapely
- pyproj>=2.2
- codecov
- coverage
- flake8
- pytest
- sphinx
- matplotlib
- numpydoc
- sphinx-copybutton
- sphinx_rtd_theme
- pip
- pip:
  - gis-utils